# 请将此文件的内容完整地覆盖到: config/config.yml

# GitHub Gist
gist:
  token: "${GITHUB_TOKEN}"
  proxy_prefix: ""
  max_result_age_hours: 24
  device_gists:
    - "aaaabbbbcccc111122223333"
    - "ddddeeeeffff444455556666"
  result_gist_id: "" # 留空则首次创建

# DNS 设置 (仅华为云)
dns:
  domain: "example.com"
  subdomain: "cf"
  ttl: 180
  lines:
    - operator: "ct"
      a_recordset_id: "12345678"
      aaaa_recordset_id: "87654321"
      cap: 2
    - operator: "cu"
      a_recordset_id: "23456789"
      aaaa_recordset_id: "98765432"
      cap: 2
    - operator: "cm"
      a_recordset_id: "34567890"
      aaaa_recordset_id: "09876543"
      cap:
