# 请将此文件的内容完整地覆盖到: config/config.yml

# GitHub Gist
gist:
  token: "${GITHUB_TOKEN}"
  proxy_prefix: ""
  max_result_age_hours: 24
  device_gists:
    - "aaaabbbbcccc111122223333"
    - "ddddeeeeffff444455556666"
  result_gist_id: "" # 留空则首次创建

# DNS 设置 (仅华为云)
# cm: 中国移动 (China Mobile)

# cu: 中国联通 (China Unicom)

# ct: 中国电信 (China Telecom)
dns:
  zone_id: "YOUR_ZONE_ID_HERE"
  domain: "example.com"
  subdomain: "cf"
  ttl: 1
  lines:
    - operator: "ct"
      a_recordset_id: "12345678"
      aaaa_recordset_id: "87654321"
      cap: 2
    - operator: "cu"
      a_recordset_id: "23456789"
      aaaa_recordset_id: "98765432"
      cap: 2
    - operator: "cm"
      a_recordset_id: "34567890"
      aaaa_recordset_id: "09876543"
      cap: 2

# 华为云项目 ID 和认证信息
huawei:
  enabled: true # 华为云更新开关
  project_id: "${HUAWEI_PROJECT_ID}"
  access_key: "${HUAWEI_ACCESS_KEY}"
  secret_key: "${HUAWEI_SECRET_KEY}"
  region: "cn-north-4"

# 打分权重
scoring:
  latency_weight: 0.5
  speed_weight:   0.3
  loss_weight:    -0.1

# 筛选阈值
thresholds:
  max_latency_ms: 80
  min_download_mbps: 10
  max_loss_pct: 1.0

# [已删除] selection 配置块已被完全移除
