name: Build and Publish
on:
  # push:
  #   branches:
  #     - main    # 在推送到主分支时触发
  # pull_request:
  #   branches:
  #     - main
#   repository_dispatch:
#     types: [upstream_repository_updated]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # 新增步骤：生成 go.sum 并自动提交
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # 根据您的项目选择合适的 Go 版本
      - name: Tidy and vendor dependencies
        run: go mod tidy
      - name: Commit updated go.mod and go.sum
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update go.mod and go.sum"
          file_pattern: go.mod go.sum

      # 后续步骤保持不变
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: | 
            ${{ secrets.DOCKER_USERNAME }}/cfst-master:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/cfst-master:latest

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
            retain_days: 0
            keep_minimum_runs: 2